site_name: AK-Sphere
site_url: https://akshaykumar-gunari.github.io/ak-sphere/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
    - navigation.footer
    - announce.dismiss
  language: en
  font:
    code: Roboto Mono
  palette:
    - scheme: default
      toggle:
        # icon: material/toggle-switch-off-outline 
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        # icon: material/toggle-switch
        icon: material/brightness-4
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/akshaykumar-gunari
    - icon: fontawesome/brands/twitter
      link: https://x.com/AkshaykumarGun2
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/akshaykumar-gunari-59b132167/
plugins:
  - blog
nav:
  - index.md
  - Blog:
    - blog/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/akshaykumar-gunari"  target="_blank" rel="noopener">Akshaykumar Gunari | AK </a>
